# Copyright 2026 SolDevelo
# Based on Bitnami MongoDB © Broadcom, Inc. (Apache-2.0)
# SPDX-License-Identifier: Apache-2.0

services:
  mongodb:
    image: docker.io/soldevelo/mongodb:9.0
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/soldevelo/mongodb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  mongodb_data:
    driver: local
